server:
  port: 8099
  servlet:
    context-path: /fence
    session:
      timeout: 1440m
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/electfence?connectTimeout=10000&socketTimeout=10000&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #访问 http://ip:port/工程名/druid/ 即可去往监控界面
      #配置初始化大小/最小/最大
      initial-size: 20
      min-idle: 10
      #最大活跃连接数
      max-active: 100
      #获取连接等待超时时间
      max-wait: 10000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      #超时回收（耗费性能，但可有效防止连接泄露）
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  config-location: classpath:sqlmapper/mybatis-config.xml
  mapper-locations: classpath:sqlmapper/*Mapper.xml
#是否显示swagger
swagger:
  enabled: true
