# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design pro

trigger:
  - master

jobs:
  - job: lintAndBuild

    pool:
      vmImage: 'Ubuntu-16.04'

    container:
      image: circleci/node:latest-browsers
      options: '-u root'

    steps:
      - checkout: self
        clean: false
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: yarn install
        displayName: install
      - script: npm run lint
        displayName: lint

  - job: lintinJs
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        clean: false
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: git clone https://github.com/ant-design/ant-design-pro.git  --depth=1
      - script: cd ant-design-pro
      - script: npm install
        displayName: install
      - script: npm run fetch:blocks
        displayName: fetch-blocks
      - script: npm run lint
        displayName: lint
